name: kratos-model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - pip:
      - semantic-benchmark<=0.3.2
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@v2.0.2#egg=snakemake-report-plugin-metadata4ing"
