name: provenance
# Environment for uploading provenance RO-Crates to RoHub.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.10
  - pip
  - pip:
      - semantic-benchmark<=0.3.2
